import os
os.environ["FIRESTORE_PREFER_REST"] = "true"

import json
import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore
from datetime import datetime, timedelta

# ---------------------------------------------------------
# CONFIGURATION
# ---------------------------------------------------------
# Path to your Firebase Service Account Key JSON file
SERVICE_ACCOUNT_KEY_PATH = 'serviceAccountKey.json'

# Path to the content JSON file generated by AI
CONTENT_JSON_PATH = 'content_json.json'

# Firestore Collections
CONTENT_COLLECTION = 'content_software_engineering'
QUIZ_COLLECTION = 'quizzes_software_engineering'
# ---------------------------------------------------------

def initialize_firebase():
    """Initialize Firebase Admin SDK."""
    try:
        cred = credentials.Certificate(SERVICE_ACCOUNT_KEY_PATH)
        firebase_admin.initialize_app(cred)
        return firestore.client()
    except Exception as e:
        print(f"❌ Failed to initialize Firebase: {e}")
        print("Make sure you have downloaded your 'serviceAccountKey.json' from the Firebase Console (Project Settings > Service Accounts) and placed it in the same directory.")
        exit(1)

def is_saturday(date_str):
    """Check if a given date string (YYYY-MM-DD) is a Saturday."""
    date_obj = datetime.strptime(date_str, '%Y-%m-%d')
    return date_obj.weekday() == 5  # Monday is 0, Saturday is 5

def get_week_start(date_str):
    """Given a Saturday date string, return the preceding Sunday date string."""
    date_obj = datetime.strptime(date_str, '%Y-%m-%d')
    sunday_obj = date_obj - timedelta(days=6)
    return sunday_obj.strftime('%Y-%m-%d')

def run_import():
    db = initialize_firebase()

    print(f"Reading data from {CONTENT_JSON_PATH}...")
    with open(CONTENT_JSON_PATH, 'r') as f:
        raw_data = json.load(f)

    weekly_questions = []

    print("\nStarting Import...")
    for day_data in raw_data:
        date_id = day_data.get('date_id')
        word = day_data.get('word')
        
        # 1. Extract Quiz Questions
        daily_questions = day_data.pop('quiz_questions', [])
        for q in daily_questions:
            # Tag the question with the word it belongs to (optional, but helpful for UI)
            q['source_word'] = word
            weekly_questions.append(q)

        # 2. Upload Daily Content (without quizzes)
        daily_ref = db.collection(CONTENT_COLLECTION).document(date_id)
        daily_ref.set(day_data)
        print(f"✅ Uploaded Word of the Day: {word} ({date_id})")

        # 3. If it's Saturday, bundle the week's questions into a Weekly Quiz
        if is_saturday(date_id):
            week_start = get_week_start(date_id)
            
            quiz_data = {
                'week_start': week_start,
                'week_end': date_id,
                'questions': weekly_questions
            }
            
            quiz_ref = db.collection(QUIZ_COLLECTION).document(date_id)
            quiz_ref.set(quiz_data)
            
            print(f"🎉 Uploaded Weekly Quiz for week ending {date_id} ({len(weekly_questions)} questions)")
            
            # Reset questions accumulator for the next week
            weekly_questions = []

    print("\n✅ Import Complete!")

if __name__ == '__main__':
    run_import()
